"""empty message

Revision ID: 1f4f7a493f7a
Revises: b138a91dd29e
Create Date: 2018-04-08 09:07:21.351473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f4f7a493f7a'
down_revision = 'b138a91dd29e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('route', sa.Column('cab_category', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('route', 'cab_category')
    # ### end Alembic commands ###
